name: Node.js Publish

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: bindings/node/package-lock.json
          registry-url: ${{ inputs.registry }}

      # TODO only update the version if it's not a tagged release
      - run: npm version ${BINDING_VERSION}-dev.${GITHUB_RUN_ID}.${GITHUB_RUN_ATTEMPT}
        working-directory: bindings/node
        env:
          BINDING_VERSION: ${{ inputs.version }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}

      - run: npm publish
        working-directory: bindings/node
        env:
          NODE_AUTH_TOKEN: ${{secrets.token}}
